// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs2JfFtPMz-WwDxCHsnOq4MVUj79lihvM',
    appId: '1:945935664981:web:cdd5e99fd6412b7c84d1dc',
    messagingSenderId: '945935664981',
    projectId: 'reach-skills',
    authDomain: 'reach-skills.firebaseapp.com',
    storageBucket: 'reach-skills.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXB-s5HP8qlPi3C5SAmCQaC3sZ5PkZ3Lw',
    appId: '1:945935664981:android:59c0f6d1a15018e784d1dc',
    messagingSenderId: '945935664981',
    projectId: 'reach-skills',
    storageBucket: 'reach-skills.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7ZJprAzRDECNUBWPp__uujTl8I9lWQD4',
    appId: '1:945935664981:ios:41d68a59efc7ff0184d1dc',
    messagingSenderId: '945935664981',
    projectId: 'reach-skills',
    storageBucket: 'reach-skills.firebasestorage.app',
    iosBundleId: 'com.whitewings.reachSkills',
  );

}