// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiPTRVsmlIB3A80quZVkkPlf1coYm1QCg',
    appId: '1:1050098823596:web:a3c98260e04739d6d28a09',
    messagingSenderId: '1050098823596',
    projectId: 'skill-swap-cf272',
    authDomain: 'skill-swap-cf272.firebaseapp.com',
    storageBucket: 'skill-swap-cf272.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLQ4qn-RpgR2TNdUMCgGy8DpSmzMV8WPY',
    appId: '1:1050098823596:android:2d7fba5ce5e84bb1d28a09',
    messagingSenderId: '1050098823596',
    projectId: 'skill-swap-cf272',
    storageBucket: 'skill-swap-cf272.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7VDJVuSodfqTCllq-H4HKva6eUVVxZlM',
    appId: '1:1050098823596:ios:12e3b25b7f6b40a7d28a09',
    messagingSenderId: '1050098823596',
    projectId: 'skill-swap-cf272',
    storageBucket: 'skill-swap-cf272.firebasestorage.app',
    iosBundleId: 'com.whitewings.skillSwap',
  );
}
